### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Aleksanaa** [RobberPhex/tg-qq-irc-bridge#1]
1.希望可以关闭显示[tencent_qq_bot]和[telegram_bot]这样的显示，因为实际使用的时候不太需要，而又比较碍眼。
2.建议增加“A回复B”的显示（当然可能有点技术难度）
除此之外，这个插件简直太棒了！我们最先找到的是Coolq Telegram bot X,但是它没法很容易地设置代理。作者只说“透明代理”，但为了这个“透明代理“我们纠缠了整整两天都没有配置上。然后找到了你的插件，完美地解决了这个问题！
希望作者再稍稍完善一下，谢谢！

**Comment by GitDjAr** [comment]
> 1.希望可以关闭显示[tencent_qq_bot]和[telegram_bot]这样的显示，因为实际使用的时候不太需要，而又比较碍眼。
> 2.建议增加“A回复B”的显示（当然可能有点技术难度）
> 除此之外，这个插件简直太棒了！我们最先找到的是Coolq Telegram bot X,但是它没法很容易地设置代理。作者只说“透明代理”，但为了这个“透明代理“我们纠缠了整整两天都没有配置上。然后找到了你的插件，完美地解决了这个问题！
> 希望作者再稍稍完善一下，谢谢！

你好,能请教一下配置细节吗,最后一个配置文件是放在那儿执行呢
